name: Multiverse-Adventure
main: com.onarandombox.MultiverseAdventure.MultiverseAdventure
author: main()
version: 1.0
depend: ['Multiverse-Core']
commands:
  mvaw:
    description: Generic Multiverse-Adventure Command
    usage: /<command>
  mvawenable:
    description: Generic Multiverse-Adventure Command
    usage: /<command>
  mvawmodify:
    description: Generic Multiverse-Adventure Command
    usage: /<command>
  mvawdisable:
    description: Generic Multiverse-Adventure Command
    usage: /<command>