name: Multiverse-Adventure
main: com.onarandombox.MultiverseAdventure.MultiverseAdventure
author: main()
version: 1.0
depend: ['Multiverse-Core']
commands:
  mva:
    description: Generic Multiverse-Adventure Command
    usage: /<command>
  mvaenable:
    description: Generic Multiverse-Adventure Command
    usage: /<command>
  mvamodify:
    description: Generic Multiverse-Adventure Command
    usage: /<command>
  mvadisable:
    description: Generic Multiverse-Adventure Command
    usage: /<command>
  mvawrite:
    description: Generic Multiverse-Adventure Command
    usage: /<command>
  mvaflush:
    description: Generic Multiverse-Adventure Command
    usage: /<command>
  mvawritetemplate:
    description: Generic Multiverse-Adventure Command
    usage: /<command>
  mvareset:
    description: Generic Multiverse-Adventure Command
    usage: /<command>